### Creating Arrays from Lists

In [1]:
import numpy as np

In [2]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array((0.1, 0.2, 0.3, 0.4))

In [3]:
a1

array([1, 2, 3, 4])

In [4]:
type(a1)

numpy.ndarray

In [5]:
a2

array([0.1, 0.2, 0.3, 0.4])

In [6]:
type(a2)

numpy.ndarray

In [7]:
a1.dtype

dtype('int32')

In [8]:
a2.dtype

dtype('float64')

In [9]:
a = np.array([1, 2, 3, 4], dtype=np.uint8)

In [11]:
a.dtype

dtype('uint8')

```[0, 255]```

In [13]:
a = np.array([1, 2, 3, 300], dtype=np.uint8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\258487933.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 300], dtype=np.uint8)


In [14]:
a

array([ 1,  2,  3, 44], dtype=uint8)

In [15]:
a = np.array([1, 2, 3, 255], dtype=np.uint8)

In [16]:
a

array([  1,   2,   3, 255], dtype=uint8)

In [17]:
a = np.array([1, 2, 3, 256], dtype=np.uint8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\2796688376.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 256 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 256], dtype=np.uint8)


In [18]:
a

array([1, 2, 3, 0], dtype=uint8)

In [19]:
a = np.array([1, 2, 3, 257], dtype=np.uint8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\2776724122.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 257 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 257], dtype=np.uint8)


In [20]:
a

array([1, 2, 3, 1], dtype=uint8)

In [21]:
a = np.array([1, 2, 3, 258], dtype=np.uint8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\2944182492.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 258 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 258], dtype=np.uint8)


In [22]:
a

array([1, 2, 3, 2], dtype=uint8)

In [23]:
a = np.array([1, 2, 3, 259], dtype=np.uint8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\3821469401.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 259 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a = np.array([1, 2, 3, 259], dtype=np.uint8)


In [24]:
a 

array([1, 2, 3, 3], dtype=uint8)

`int8: [-128, 127]`

In [26]:
np.array([127], dtype=np.int8)

array([127], dtype=int8)

In [27]:
np.array([128], dtype=np.int8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\520780534.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 128 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([128], dtype=np.int8)


array([-128], dtype=int8)

In [28]:
np.array([129], dtype=np.int8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\961925688.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 129 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([129], dtype=np.int8)


array([-127], dtype=int8)

In [29]:
np.array([130], dtype=np.int8)

C:\Users\Oxward\AppData\Local\Temp\ipykernel_8244\738084946.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 130 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  np.array([130], dtype=np.int8)


array([-126], dtype=int8)

In [30]:
a = np.array([1, 2, 3.14])

In [31]:
a

array([1.  , 2.  , 3.14])

In [32]:
a.dtype

dtype('float64')

In [33]:
a = np.array([1, 2, 9.9, 9.1], dtype=np.int64)

In [34]:
a

array([1, 2, 9, 9], dtype=int64)

In [35]:
a = np.array([1, 3.14, 'x'])

In [36]:
a.dtype

dtype('<U32')

In [37]:
a

array(['1', '3.14', 'x'], dtype='<U32')

In [38]:
a = np.array([1, 3.14, 'x'], dtype=np.int64)

ValueError: invalid literal for int() with base 10: 'x'

In [39]:
a = np.array([1, 3.14, 'x'], dtype=np.float64)

ValueError: could not convert string to float: 'x'

In [40]:
m_py = [
    [1, 0, 0],
    [0, 1, 0],
    [0, 0, 1]
]

In [41]:
m_py

[[1, 0, 0], [0, 1, 0], [0, 0, 1]]

In [42]:
m1 = np.array(m_py, dtype=np.int64)

In [44]:
m1

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int64)

In [45]:
m1.dtype

dtype('int64')

In [46]:
len(m_py)

3

In [47]:
a = np.array([1, 2, 3])
m2 = np.array(
    [
        [1, 2, 3],
        [4, 5, 6],
        [7, 8, 9],
        [10, 11, 12]
    ]
)

In [48]:
a.size

3

In [49]:
m2.size

12

In [50]:
m1.size

9

In [51]:
a.shape

(3,)

In [52]:
m1.shape

(3, 3)

In [53]:
m2.shape

(4, 3)

### Creating Arrays from Scratch

In [54]:
import numpy as np

In [56]:
a = np.zeros(5)

In [57]:
a

array([0., 0., 0., 0., 0.])

In [58]:
a.dtype

dtype('float64')

In [59]:
a = np.zeros(5, dtype=int)

In [60]:
a.dtype

dtype('int32')

In [61]:
a = np.zeros(5, dtype=float)

In [62]:
a.dtype

dtype('float64')

In [63]:
a

array([0., 0., 0., 0., 0.])

In [64]:
a = np.zeros(5, dtype=int)

In [65]:
a

array([0, 0, 0, 0, 0])

In [66]:
a = np.zeros((4, 3), dtype=np.uint8)

In [67]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint8)

In [68]:
m = np.ones((10, 2), dtype=float)

In [69]:
m

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [70]:
m.dtype

dtype('float64')

In [71]:
m = np.full((2, 5), 3.14, dtype=np.float32)

In [72]:
m

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]], dtype=float32)

In [73]:
m.dtype

dtype('float32')

In [74]:
m = np.eye(5)

In [75]:
m

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [76]:
m = np.eye(5, dtype=int)

In [77]:
m

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [78]:
m.dtype

dtype('int32')

In [79]:
m = np.eye(5, 3, dtype=np.uint16)

In [80]:
m

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1],
       [0, 0, 0],
       [0, 0, 0]], dtype=uint16)

In [81]:
list(range(2, 11, 2))

[2, 4, 6, 8, 10]

In [82]:
np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

In [83]:
np.arange(2, 11, 2, dtype=np.uint8)

array([ 2,  4,  6,  8, 10], dtype=uint8)

In [84]:
np.linspace(2, 10, num=5)

array([ 2.,  4.,  6.,  8., 10.])

In [85]:
np.linspace(2, 10)

array([ 2.        ,  2.16326531,  2.32653061,  2.48979592,  2.65306122,
        2.81632653,  2.97959184,  3.14285714,  3.30612245,  3.46938776,
        3.63265306,  3.79591837,  3.95918367,  4.12244898,  4.28571429,
        4.44897959,  4.6122449 ,  4.7755102 ,  4.93877551,  5.10204082,
        5.26530612,  5.42857143,  5.59183673,  5.75510204,  5.91836735,
        6.08163265,  6.24489796,  6.40816327,  6.57142857,  6.73469388,
        6.89795918,  7.06122449,  7.2244898 ,  7.3877551 ,  7.55102041,
        7.71428571,  7.87755102,  8.04081633,  8.20408163,  8.36734694,
        8.53061224,  8.69387755,  8.85714286,  9.02040816,  9.18367347,
        9.34693878,  9.51020408,  9.67346939,  9.83673469, 10.        ])

In [86]:
np.linspace(2, 10, 10)

array([ 2.        ,  2.88888889,  3.77777778,  4.66666667,  5.55555556,
        6.44444444,  7.33333333,  8.22222222,  9.11111111, 10.        ])

In [87]:
import math

In [89]:
x_coords = np.linspace(-2 * math.pi, 2 * math.pi, 50)

In [90]:
x_coords

array([-6.28318531, -6.02672876, -5.77027222, -5.51381568, -5.25735913,
       -5.00090259, -4.74444605, -4.48798951, -4.23153296, -3.97507642,
       -3.71861988, -3.46216333, -3.20570679, -2.94925025, -2.6927937 ,
       -2.43633716, -2.17988062, -1.92342407, -1.66696753, -1.41051099,
       -1.15405444, -0.8975979 , -0.64114136, -0.38468481, -0.12822827,
        0.12822827,  0.38468481,  0.64114136,  0.8975979 ,  1.15405444,
        1.41051099,  1.66696753,  1.92342407,  2.17988062,  2.43633716,
        2.6927937 ,  2.94925025,  3.20570679,  3.46216333,  3.71861988,
        3.97507642,  4.23153296,  4.48798951,  4.74444605,  5.00090259,
        5.25735913,  5.51381568,  5.77027222,  6.02672876,  6.28318531])

In [91]:
y_values = np.array([math.sin(x) for x in x_coords])

In [92]:
y_values

array([ 2.44929360e-16,  2.53654584e-01,  4.90717552e-01,  6.95682551e-01,
        8.55142763e-01,  9.58667853e-01,  9.99486216e-01,  9.74927912e-01,
        8.86599306e-01,  7.40277997e-01,  5.45534901e-01,  3.15108218e-01,
        6.40702200e-02, -1.91158629e-01, -4.33883739e-01, -6.48228395e-01,
       -8.20172255e-01, -9.38468422e-01, -9.95379113e-01, -9.87181783e-01,
       -9.14412623e-01, -7.81831482e-01, -5.98110530e-01, -3.75267005e-01,
       -1.27877162e-01,  1.27877162e-01,  3.75267005e-01,  5.98110530e-01,
        7.81831482e-01,  9.14412623e-01,  9.87181783e-01,  9.95379113e-01,
        9.38468422e-01,  8.20172255e-01,  6.48228395e-01,  4.33883739e-01,
        1.91158629e-01, -6.40702200e-02, -3.15108218e-01, -5.45534901e-01,
       -7.40277997e-01, -8.86599306e-01, -9.74927912e-01, -9.99486216e-01,
       -9.58667853e-01, -8.55142763e-01, -6.95682551e-01, -4.90717552e-01,
       -2.53654584e-01, -2.44929360e-16])

In [93]:
np.random.random(5)

array([0.51060346, 0.40950369, 0.42954335, 0.76906532, 0.50923117])

In [95]:
np.random.seed(0)

np.random.random(5)

array([0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ])

In [96]:
np.random.seed(0)

np.random.random((5, 3))

array([[0.5488135 , 0.71518937, 0.60276338],
       [0.54488318, 0.4236548 , 0.64589411],
       [0.43758721, 0.891773  , 0.96366276],
       [0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606]])

In [98]:
np.random.seed(0)

np.random.randint(1, 10, 50)

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6, 9, 5,
       4, 1, 4, 6, 1, 3, 4, 9, 2, 4, 4, 4, 8, 1, 2, 1, 5, 8, 4, 3, 8, 3,
       1, 1, 5, 6, 6, 7])

In [99]:
from numpy import random as npr

In [100]:
npr.seed(0)

npr.randint(1, 6 + 1, 10)

array([5, 6, 1, 4, 4, 4, 2, 4, 6, 3])

In [101]:
npr.seed(0)

npr.randint(1, 7, (10, 2))

array([[5, 6],
       [1, 4],
       [4, 4],
       [2, 4],
       [6, 3],
       [5, 1],
       [1, 5],
       [3, 2],
       [1, 2],
       [6, 2]])

In [102]:
npr.seed(0)

npr.randint(1, 7, (10, 5))

array([[5, 6, 1, 4, 4],
       [4, 2, 4, 6, 3],
       [5, 1, 1, 5, 3],
       [2, 1, 2, 6, 2],
       [6, 1, 2, 5, 4],
       [1, 4, 6, 1, 3],
       [4, 1, 2, 4, 6],
       [4, 4, 1, 2, 2],
       [2, 1, 3, 5, 4],
       [4, 3, 5, 3, 1]])

### Reshaping Arrays

In [1]:
import numpy as np

In [2]:
arr = np.arange(12)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [4]:
arr.shape

(12,)

In [5]:
m1 = arr.reshape(4, 3)

In [6]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [7]:
m2 = arr.reshape(2, 6)

In [8]:
m2

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [9]:
m3 = m2.reshape(6, 2)

In [10]:
m3

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [11]:
arr is m1

False

In [12]:
m2 is m3

False

In [13]:
m1 is m2

False

In [14]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [15]:
m1

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [16]:
arr[0] = 100

In [17]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11])

In [18]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10,  11]])

In [19]:
m2 

array([[100,   1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10,  11]])

In [20]:
m3

array([[100,   1],
       [  2,   3],
       [  4,   5],
       [  6,   7],
       [  8,   9],
       [ 10,  11]])

In [21]:
m1[3][2] = 200

In [22]:
m1

array([[100,   1,   2],
       [  3,   4,   5],
       [  6,   7,   8],
       [  9,  10, 200]])

In [23]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [24]:
m3 = arr.reshape(3, 4).copy()

In [25]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [26]:
m3[0][0] = 0

In [27]:
m3

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [28]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [29]:
m3 = arr.copy().reshape(3, 4)

In [30]:
m3

array([[100,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [31]:
m3[0][0] = 0

In [32]:
m3

array([[  0,   1,   2,   3],
       [  4,   5,   6,   7],
       [  8,   9,  10, 200]])

In [33]:
arr

array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10, 200])

In [34]:
m = np.array(
    [
        [1, 2, 3],
        [4, 5, 6]
    ]
)

In [35]:
m.shape

(2, 3)

In [36]:
arr2 = m.reshape((6, ))
arr2

array([1, 2, 3, 4, 5, 6])

In [37]:
arr2= m.reshape(6)

In [39]:
arr2

array([1, 2, 3, 4, 5, 6])

In [40]:
arr2[2] = 30
arr2

array([ 1,  2, 30,  4,  5,  6])

In [41]:
m

array([[ 1,  2, 30],
       [ 4,  5,  6]])

In [42]:
np.arange(1, 11).reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

### Stacking Arrays

In [1]:
import numpy as np

In [2]:
a1 = np.arange(1, 6)
a1

array([1, 2, 3, 4, 5])

In [3]:
a2 = np.arange(1, 11).reshape(2, 5)
a2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [5]:
s1 = np.vstack((a1, a2))
s1

array([[ 1,  2,  3,  4,  5],
       [ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [6]:
try:
    np.vstack((np.arange(3), a2))
except ValueError as ex:
    print(ex)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 5


In [7]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([0.1, 0.2, 0.3, 0.4])
result = np.vstack((a1, a2))
result

array([[1. , 2. , 3. , 4. ],
       [0.1, 0.2, 0.3, 0.4]])

In [8]:
result.dtype

dtype('float64')

In [9]:
a1 = np.array([1, 2, 3, 4], dtype=np.uint8)
a2 = np.array([1000, 2000, 3000, 40000], dtype=np.uint8)
result = np.vstack((a1, a2))
result

C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\2643957257.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 1000 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a2 = np.array([1000, 2000, 3000, 40000], dtype=np.uint8)
C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\2643957257.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  a2 = np.array([1000, 2000, 3000, 40000], dtype=np.uint8)
C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\2643957257.py:2: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The convers

array([[  1,   2,   3,   4],
       [232, 208, 184,  64]], dtype=uint8)

In [10]:
np.vstack(
    (
        np.arange(5),
        np.linspace(0, 1, 5),
        np.eye(5)
    )
)

array([[0.  , 1.  , 2.  , 3.  , 4.  ],
       [0.  , 0.25, 0.5 , 0.75, 1.  ],
       [1.  , 0.  , 0.  , 0.  , 0.  ],
       [0.  , 1.  , 0.  , 0.  , 0.  ],
       [0.  , 0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.  , 0.  , 1.  , 0.  ],
       [0.  , 0.  , 0.  , 0.  , 1.  ]])

In [11]:
a1 = np.array([1, 2], dtype=np.uint8)
a2 = np.array([2, 3], dtype=np.uint64)
a3 = np.array([4, 5], dtype=np.int32)

result = np.vstack([a1, a2, a3])
result

array([[1., 2.],
       [2., 3.],
       [4., 5.]])

In [12]:
result.dtype

dtype('float64')

In [13]:
a1

array([1, 2], dtype=uint8)

In [14]:
a2.astype(np.float32)

array([2., 3.], dtype=float32)

In [15]:
result = np.vstack(
    (
        a1.astype(np.int64),
        a1.astype(int),
        a3.astype(np.int64)
    )
)

In [16]:
result

array([[1, 2],
       [1, 2],
       [4, 5]], dtype=int64)

In [17]:
result.dtype

dtype('int64')

In [18]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([10, 20, 30, 40])
result = np.vstack((a1, a2))
result

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [19]:
a1[0] = 100
a1

array([100,   2,   3,   4])

In [20]:
result

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [21]:
result[1][2] = 300

In [22]:
result

array([[  1,   2,   3,   4],
       [ 10,  20, 300,  40]])

In [23]:
a2

array([10, 20, 30, 40])

In [24]:
a1 = np.linspace(0, 5, 10).reshape(5, 2)
a1

array([[0.        , 0.55555556],
       [1.11111111, 1.66666667],
       [2.22222222, 2.77777778],
       [3.33333333, 3.88888889],
       [4.44444444, 5.        ]])

In [25]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 10).reshape(5, 2)
a2

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4]])

In [26]:
result = np.hstack((a1, a2))
result

array([[0.        , 0.55555556, 5.        , 0.        ],
       [1.11111111, 1.66666667, 3.        , 3.        ],
       [2.22222222, 2.77777778, 7.        , 9.        ],
       [3.33333333, 3.88888889, 3.        , 5.        ],
       [4.44444444, 5.        , 2.        , 4.        ]])

In [27]:
np.random.seed(0)
a2 = np.random.randint(0, 10, 20).reshape(5, 4)
a2

array([[5, 0, 3, 3],
       [7, 9, 3, 5],
       [2, 4, 7, 6],
       [8, 8, 1, 6],
       [7, 7, 8, 1]])

In [28]:
result = np.hstack((a1, a2))
result

array([[0.        , 0.55555556, 5.        , 0.        , 3.        ,
        3.        ],
       [1.11111111, 1.66666667, 7.        , 9.        , 3.        ,
        5.        ],
       [2.22222222, 2.77777778, 2.        , 4.        , 7.        ,
        6.        ],
       [3.33333333, 3.88888889, 8.        , 8.        , 1.        ,
        6.        ],
       [4.44444444, 5.        , 7.        , 7.        , 8.        ,
        1.        ]])

### Indexing

In [29]:
import numpy as np

In [30]:
a = [1, 2, 3, 4]
a[2]

3

In [31]:
m = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [32]:
m[1]

[4, 5, 6]

In [33]:
m[1][1]

5

In [35]:
m[1][2] = 100

In [36]:
m

[[1, 2, 3], [4, 5, 100], [7, 8, 9]]

In [37]:
a = np.array([1, 2, 3])

In [38]:
a[0]

1

In [39]:
a[1] = 200

In [40]:
a

array([  1, 200,   3])

In [41]:
m = np.eye(3)
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [42]:
m[1][1]

1.0

In [43]:
m[1, 1]

1.0

In [44]:
m[1, 2] = 100
m

array([[  1.,   0.,   0.],
       [  0.,   1., 100.],
       [  0.,   0.,   1.]])

In [45]:
m[(1, 2)]

100.0

In [46]:
m[1, 2]

100.0

In [47]:
m[1]

array([  0.,   1., 100.])

In [48]:
m[1, 1]

1.0

In [49]:
m[1, 2] = 0
m

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [50]:
arr = np.array([1, 2, 3, 4], dtype=np.uint8)
arr

array([1, 2, 3, 4], dtype=uint8)

In [52]:
arr[0] = -100

C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\1768485359.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -100 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[0] = -100


In [53]:
arr

array([156,   2,   3,   4], dtype=uint8)

### Slicing

In [54]:
import numpy as np

In [55]:
l = [1, 2, 3, 4, 5, 6]

In [56]:
l[0:3]

[1, 2, 3]

In [57]:
l[0::2]

[1, 3, 5]

In [58]:
l[::-1]

[6, 5, 4, 3, 2, 1]

In [59]:
arr = np.array(l)

In [61]:
arr[0:3]

array([1, 2, 3])

In [63]:
arr[0::2]

array([1, 3, 5])

In [64]:
arr[::-1]

array([6, 5, 4, 3, 2, 1])

In [65]:
l

[1, 2, 3, 4, 5, 6]

In [67]:
slice_ = l[0:2]
slice_

[1, 2]

In [68]:
slice_[0] = 100
slice_

[100, 2]

In [69]:
l

[1, 2, 3, 4, 5, 6]

In [70]:
arr = np.array(l)
arr

array([1, 2, 3, 4, 5, 6])

In [71]:
slice_ = arr[0:2]
slice_

array([1, 2])

In [72]:
slice_[0] = 100
slice_

array([100,   2])

In [73]:
arr

array([100,   2,   3,   4,   5,   6])

In [74]:
arr = np.arange(1, 7)
slice_ = arr[3:]
slice_

array([4, 5, 6])

In [75]:
arr[-1] = 60
arr

array([ 1,  2,  3,  4,  5, 60])

In [76]:
slice_

array([ 4,  5, 60])

In [77]:
arr = np.arange(1, 7)
slice_ = arr[3:].copy()
slice_

array([4, 5, 6])

In [78]:
slice_[0] = 40
slice_

array([40,  5,  6])

In [79]:
arr

array([1, 2, 3, 4, 5, 6])

In [80]:
arr = np.arange(1, 26).reshape(5, 5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [81]:
arr[0:2, 0:2]

array([[1, 2],
       [6, 7]])

In [82]:
arr[0::2, 0::2]

array([[ 1,  3,  5],
       [11, 13, 15],
       [21, 23, 25]])

In [83]:
arr[2, 1::2]

array([12, 14])

In [84]:
slice_ = arr[2, 1::2]
slice_

array([12, 14])

In [85]:
slice_[0] = 120
slice_

array([120,  14])

In [86]:
arr

array([[  1,   2,   3,   4,   5],
       [  6,   7,   8,   9,  10],
       [ 11, 120,  13,  14,  15],
       [ 16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25]])

In [87]:
l = [1, 2, 3, 4, 5, 6]

In [88]:
l[0:3] = [10, 20, 30]

In [89]:
l

[10, 20, 30, 4, 5, 6]

In [90]:
l = [1, 2, 3, 4, 5, 6]
l[0:3] = [10, 20, 30, 40, 50, 60]
l

[10, 20, 30, 40, 50, 60, 4, 5, 6]

In [91]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = np.array([10, 20, 30])
arr

array([10, 20, 30,  4,  5,  6])

In [92]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = [10, 30, 50]
arr

array([10, 30, 50,  4,  5,  6])

In [93]:
arr = np.array([1, 2, 3, 4, 5, 6])
arr[0:3] = [10, 20, 30, 40]
arr

ValueError: could not broadcast input array from shape (4,) into shape (3,)

In [94]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [95]:
arr[::2, ::2]

array([[0, 2],
       [6, 8]])

In [96]:
arr[::2, ::2] = [[10, 20], [30, 40]]
arr

array([[10,  1, 20],
       [ 3,  4,  5],
       [30,  7, 40]])

In [97]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [98]:
arr[::2, ::2] = 100
arr

array([[100,   1, 100],
       [  3,   4,   5],
       [100,   7, 100]])

In [99]:
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20])

In [101]:
arr1[0:2] = arr2
arr1

array([10, 20,  3,  4,  5])

In [102]:
arr2[0] = 100
arr2

array([100,  20])

In [103]:
arr1

array([10, 20,  3,  4,  5])

In [104]:
arr = np.arange(9).reshape(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [105]:
arr[:2, 1:]

array([[1, 2],
       [4, 5]])

In [106]:
arr[:2, 1:] = [[10, 20], [40, 50]]
arr

array([[ 0, 10, 20],
       [ 3, 40, 50],
       [ 6,  7,  8]])

In [107]:
arr[:2, 1:] = [10, 20, 40, 50]

ValueError: could not broadcast input array from shape (4,) into shape (2,2)

In [108]:
arr[:2, 1:] = np.array([10, 20, 40, 50]).reshape(2, 2)
arr

array([[ 0, 10, 20],
       [ 3, 40, 50],
       [ 6,  7,  8]])

In [109]:
arr = np.array([10, 20, 30, 40, 50], dtype=np.uint8)
arr

array([10, 20, 30, 40, 50], dtype=uint8)

In [110]:
arr[0:2] = [-100, 300]
arr

C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\3365488855.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of -100 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[0:2] = [-100, 300]
C:\Users\Oxward\AppData\Local\Temp\ipykernel_5492\3365488855.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 300 to uint8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[0:2] = [-100, 300]


array([156,  44,  30,  40,  50], dtype=uint8)

### Fancy Indexing

In [111]:
import numpy as np

In [112]:
arr = np.arange(10, 100, 10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [113]:
sub = [arr[0], arr[2], arr[3]]
sub

[10, 30, 40]

In [114]:
sub = arr[np.array([0, 2, 3])]
sub

array([10, 30, 40])

In [115]:
arr[[0, 2, 3]]

array([10, 30, 40])

In [116]:
arr[0, 2, 3]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [117]:
arr[(0, 2, 3)]

IndexError: too many indices for array: array is 1-dimensional, but 3 were indexed

In [118]:
arr[[0, 2, 3]]

array([10, 30, 40])

In [119]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [120]:
sub = arr[np.array([0, 2, 3])]
sub

array([10, 30, 40])

In [121]:
sub[0] = 100
sub

array([100,  30,  40])

In [122]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [123]:
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [124]:
arr[np.array([0, 1, 1, 5])]

array([1, 2, 2, 6])

In [126]:
arr[np.array([
    [0, 1],
    [1, 5]
])]

array([[1, 2],
       [2, 6]])

In [127]:
m = np.arange(25).reshape(5, 5)
m

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [128]:
m[[0, 1, 3]]

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [15, 16, 17, 18, 19]])

In [129]:
m[[0, 1, 3], 2]

array([ 2,  7, 17])

In [130]:
m[[0, 1, 3], 0::2]

array([[ 0,  2,  4],
       [ 5,  7,  9],
       [15, 17, 19]])

In [131]:
m[np.array([0, 1, 3]), np.array([1, 2, 4])]

array([ 1,  7, 19])

```
04      14      (0, 1) (4, 4)

23      24      (2, 2) (3, 4)
```

In [132]:
m[
    [[0, 4], [2, 3]],
    [[1, 4], [2, 4]]
]

array([[ 1, 24],
       [12, 19]])

In [133]:
import csv

In [134]:
with open('files/AAPL.csv') as f:
    reader = csv.reader(f, skipinitialspace=True)
    headers = next(reader)
    data = list(reader)

In [135]:
headers

['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']

In [136]:
data

[['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93', '112.2'],
 ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43', '111.1'],
 ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28', '114.5399'],
 ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55', '112.88'],
 ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55', '114.28'],
 ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04', '114.59'],
 ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705', '116.45'],
 ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98', '115.63'],
 ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419', '115.66'],
 ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548', '118.81'],
 ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2', '118.15'],
 ['AAPL', '10/14/2020', '121.19', '151062300', '121', '123.03', '119.62'],
 ['AAPL', '10/13/2020', '121.1', '262330500', '125.27', '125.39', '119.

In [137]:
data = np.array(data)
data

array([['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93',
        '112.2'],
       ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43',
        '111.1'],
       ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28',
        '114.5399'],
       ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55',
        '112.88'],
       ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55',
        '114.28'],
       ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04',
        '114.59'],
       ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705',
        '116.45'],
       ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98',
        '115.63'],
       ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419',
        '115.66'],
       ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548',
        '118.81'],
       ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2',
        '11

In [138]:
dates = data[:, 1]
dates

array(['10/29/2020', '10/28/2020', '10/27/2020', '10/26/2020',
       '10/23/2020', '10/22/2020', '10/21/2020', '10/20/2020',
       '10/19/2020', '10/16/2020', '10/15/2020', '10/14/2020',
       '10/13/2020', '10/12/2020', '10/09/2020', '10/08/2020',
       '10/07/2020', '10/06/2020', '10/05/2020', '10/02/2020',
       '10/01/2020', '09/30/2020', '09/29/2020'], dtype='<U10')

In [139]:
from dateutil import parser

In [141]:
dates = [parser.parse(d) for d in dates]
dates

[datetime.datetime(2020, 10, 29, 0, 0),
 datetime.datetime(2020, 10, 28, 0, 0),
 datetime.datetime(2020, 10, 27, 0, 0),
 datetime.datetime(2020, 10, 26, 0, 0),
 datetime.datetime(2020, 10, 23, 0, 0),
 datetime.datetime(2020, 10, 22, 0, 0),
 datetime.datetime(2020, 10, 21, 0, 0),
 datetime.datetime(2020, 10, 20, 0, 0),
 datetime.datetime(2020, 10, 19, 0, 0),
 datetime.datetime(2020, 10, 16, 0, 0),
 datetime.datetime(2020, 10, 15, 0, 0),
 datetime.datetime(2020, 10, 14, 0, 0),
 datetime.datetime(2020, 10, 13, 0, 0),
 datetime.datetime(2020, 10, 12, 0, 0),
 datetime.datetime(2020, 10, 9, 0, 0),
 datetime.datetime(2020, 10, 8, 0, 0),
 datetime.datetime(2020, 10, 7, 0, 0),
 datetime.datetime(2020, 10, 6, 0, 0),
 datetime.datetime(2020, 10, 5, 0, 0),
 datetime.datetime(2020, 10, 2, 0, 0),
 datetime.datetime(2020, 10, 1, 0, 0),
 datetime.datetime(2020, 9, 30, 0, 0),
 datetime.datetime(2020, 9, 29, 0, 0)]

In [142]:
headers

['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']

In [143]:
oc = data[:, [4, 2]]
oc

array([['112.37', '115.32'],
       ['115.05', '111.2'],
       ['115.49', '116.6'],
       ['114.01', '115.05'],
       ['116.39', '115.04'],
       ['117.45', '115.75'],
       ['116.67', '116.87'],
       ['116.2', '117.51'],
       ['119.96', '115.98'],
       ['121.28', '119.02'],
       ['118.72', '120.71'],
       ['121', '121.19'],
       ['125.27', '121.1'],
       ['120.06', '124.4'],
       ['115.28', '116.97'],
       ['116.25', '114.97'],
       ['114.62', '115.08'],
       ['115.7', '113.16'],
       ['113.91', '116.5'],
       ['112.89', '113.02'],
       ['117.64', '116.79'],
       ['113.79', '115.81'],
       ['114.55', '114.09']], dtype='<U10')

In [145]:
oc = data[:, [4, 2]].astype(float)
oc

array([[112.37, 115.32],
       [115.05, 111.2 ],
       [115.49, 116.6 ],
       [114.01, 115.05],
       [116.39, 115.04],
       [117.45, 115.75],
       [116.67, 116.87],
       [116.2 , 117.51],
       [119.96, 115.98],
       [121.28, 119.02],
       [118.72, 120.71],
       [121.  , 121.19],
       [125.27, 121.1 ],
       [120.06, 124.4 ],
       [115.28, 116.97],
       [116.25, 114.97],
       [114.62, 115.08],
       [115.7 , 113.16],
       [113.91, 116.5 ],
       [112.89, 113.02],
       [117.64, 116.79],
       [113.79, 115.81],
       [114.55, 114.09]])

In [146]:
diffs = oc[:, 1] - oc[:, 0]
diffs

array([ 2.95, -3.85,  1.11,  1.04, -1.35, -1.7 ,  0.2 ,  1.31, -3.98,
       -2.26,  1.99,  0.19, -4.17,  4.34,  1.69, -1.28,  0.46, -2.54,
        2.59,  0.13, -0.85,  2.02, -0.46])

In [148]:
diff_percs = (oc[:, 1] - oc[:, 0]) / oc[:, 0] * 100
diff_percs

array([ 2.62525585, -3.34637114,  0.96112218,  0.91220068, -1.15989346,
       -1.44742444,  0.17142367,  1.12736661, -3.31777259, -1.86345646,
        1.67621294,  0.15702479, -3.32880977,  3.61485924,  1.46599584,
       -1.10107527,  0.40132612, -2.19533276,  2.27372487,  0.11515635,
       -0.72254335,  1.77519993, -0.40157137])

### Masking

In [149]:
import numpy as np

In [150]:
m = np.array([-1, 1, -2, 2, -3, 3])
m

array([-1,  1, -2,  2, -3,  3])

In [151]:
np.less(m, 0)

array([ True, False,  True, False,  True, False])

In [152]:
m < 0

array([ True, False,  True, False,  True, False])

In [153]:
np.greater(m, 0)

array([False,  True, False,  True, False,  True])

In [154]:
m > 0

array([False,  True, False,  True, False,  True])

In [155]:
mask = m > 0
mask

array([False,  True, False,  True, False,  True])

In [156]:
m[mask]

array([1, 2, 3])

In [157]:
m[m > 0]

array([1, 2, 3])

In [158]:
m1 = np.array([1, 2, 3, 4, 5, 6])

In [159]:
m1[m > 0]

array([2, 4, 6])

In [160]:
m = np.array(
    [
        [-1, 1, -2, 2],
        [-3, 3, -4, 4],
        [-5, 5, -6, 6]
    ]
)

In [161]:
m

array([[-1,  1, -2,  2],
       [-3,  3, -4,  4],
       [-5,  5, -6,  6]])

In [162]:
m < 0

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [163]:
m[m<0]

array([-1, -2, -3, -4, -5, -6])

In [165]:
m < -1

array([[False, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [164]:
m[m < -1]

array([-2, -3, -4, -5, -6])

In [167]:
arr = np.arange(-5, 6)
arr

array([-5, -4, -3, -2, -1,  0,  1,  2,  3,  4,  5])

In [168]:
mask = arr > 0 & arr < 4

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [169]:
mask = (arr > 0) & (arr < 4)
mask

array([False, False, False, False, False, False,  True,  True,  True,
       False, False])

In [170]:
arr[mask]

array([1, 2, 3])

In [171]:
arr[(arr > 0) & (arr < 4)]

array([1, 2, 3])

In [172]:
arr[~(arr < 0)]

array([0, 1, 2, 3, 4, 5])

In [173]:
arr[arr >= 0]

array([0, 1, 2, 3, 4, 5])

In [174]:
import csv
from dateutil import parser

In [175]:
with open('files/AAPL.csv') as f:
    reader = csv.reader(f, skipinitialspace=True)
    headers = next(reader)
    data = list(reader)

print(headers)
for row in data:
    print(data)

['Symbol', 'Date', 'Close', 'Volume', 'Open', 'High', 'Low']
[['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93', '112.2'], ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43', '111.1'], ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28', '114.5399'], ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55', '112.88'], ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55', '114.28'], ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04', '114.59'], ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705', '116.45'], ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98', '115.63'], ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419', '115.66'], ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548', '118.81'], ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2', '118.15'], ['AAPL', '10/14/2020', '121.19', '151062300', '121', '123.03', '119.62'], ['AAPL', '10/13/2020'

In [177]:
arr = np.array(data)
arr

array([['AAPL', '10/29/2020', '115.32', '146129200', '112.37', '116.93',
        '112.2'],
       ['AAPL', '10/28/2020', '111.2', '143937800', '115.05', '115.43',
        '111.1'],
       ['AAPL', '10/27/2020', '116.6', '92276770', '115.49', '117.28',
        '114.5399'],
       ['AAPL', '10/26/2020', '115.05', '111850700', '114.01', '116.55',
        '112.88'],
       ['AAPL', '10/23/2020', '115.04', '82572650', '116.39', '116.55',
        '114.28'],
       ['AAPL', '10/22/2020', '115.75', '101988000', '117.45', '118.04',
        '114.59'],
       ['AAPL', '10/21/2020', '116.87', '89945980', '116.67', '118.705',
        '116.45'],
       ['AAPL', '10/20/2020', '117.51', '124423700', '116.2', '118.98',
        '115.63'],
       ['AAPL', '10/19/2020', '115.98', '120639300', '119.96', '120.419',
        '115.66'],
       ['AAPL', '10/16/2020', '119.02', '115393800', '121.28', '121.548',
        '118.81'],
       ['AAPL', '10/15/2020', '120.71', '112559200', '118.72', '121.2',
        '11

In [178]:
dates = np.array([parser.parse(dt) for dt in arr[:, 1]])
dates

array([datetime.datetime(2020, 10, 29, 0, 0),
       datetime.datetime(2020, 10, 28, 0, 0),
       datetime.datetime(2020, 10, 27, 0, 0),
       datetime.datetime(2020, 10, 26, 0, 0),
       datetime.datetime(2020, 10, 23, 0, 0),
       datetime.datetime(2020, 10, 22, 0, 0),
       datetime.datetime(2020, 10, 21, 0, 0),
       datetime.datetime(2020, 10, 20, 0, 0),
       datetime.datetime(2020, 10, 19, 0, 0),
       datetime.datetime(2020, 10, 16, 0, 0),
       datetime.datetime(2020, 10, 15, 0, 0),
       datetime.datetime(2020, 10, 14, 0, 0),
       datetime.datetime(2020, 10, 13, 0, 0),
       datetime.datetime(2020, 10, 12, 0, 0),
       datetime.datetime(2020, 10, 9, 0, 0),
       datetime.datetime(2020, 10, 8, 0, 0),
       datetime.datetime(2020, 10, 7, 0, 0),
       datetime.datetime(2020, 10, 6, 0, 0),
       datetime.datetime(2020, 10, 5, 0, 0),
       datetime.datetime(2020, 10, 2, 0, 0),
       datetime.datetime(2020, 10, 1, 0, 0),
       datetime.datetime(2020, 9, 30, 0, 

In [179]:
ohlc = arr[:, [4, 5, 6, 2]].astype(float)

In [180]:
ohlc

array([[112.37  , 116.93  , 112.2   , 115.32  ],
       [115.05  , 115.43  , 111.1   , 111.2   ],
       [115.49  , 117.28  , 114.5399, 116.6   ],
       [114.01  , 116.55  , 112.88  , 115.05  ],
       [116.39  , 116.55  , 114.28  , 115.04  ],
       [117.45  , 118.04  , 114.59  , 115.75  ],
       [116.67  , 118.705 , 116.45  , 116.87  ],
       [116.2   , 118.98  , 115.63  , 117.51  ],
       [119.96  , 120.419 , 115.66  , 115.98  ],
       [121.28  , 121.548 , 118.81  , 119.02  ],
       [118.72  , 121.2   , 118.15  , 120.71  ],
       [121.    , 123.03  , 119.62  , 121.19  ],
       [125.27  , 125.39  , 119.65  , 121.1   ],
       [120.06  , 125.18  , 119.2845, 124.4   ],
       [115.28  , 117.    , 114.92  , 116.97  ],
       [116.25  , 116.4   , 114.5901, 114.97  ],
       [114.62  , 115.55  , 114.13  , 115.08  ],
       [115.7   , 116.12  , 112.25  , 113.16  ],
       [113.91  , 116.65  , 113.55  , 116.5   ],
       [112.89  , 115.37  , 112.22  , 113.02  ],
       [117.64  , 11

In [182]:
ohlc[:, 3] > 116.0

array([False, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True, False, False])

In [183]:
ohlc[ohlc[:, 3] > 116.0]

array([[115.49  , 117.28  , 114.5399, 116.6   ],
       [116.67  , 118.705 , 116.45  , 116.87  ],
       [116.2   , 118.98  , 115.63  , 117.51  ],
       [121.28  , 121.548 , 118.81  , 119.02  ],
       [118.72  , 121.2   , 118.15  , 120.71  ],
       [121.    , 123.03  , 119.62  , 121.19  ],
       [125.27  , 125.39  , 119.65  , 121.1   ],
       [120.06  , 125.18  , 119.2845, 124.4   ],
       [115.28  , 117.    , 114.92  , 116.97  ],
       [113.91  , 116.65  , 113.55  , 116.5   ],
       [117.64  , 117.72  , 115.83  , 116.79  ]])

In [184]:
dates[ohlc[:, 3] > 116.0]

array([datetime.datetime(2020, 10, 27, 0, 0),
       datetime.datetime(2020, 10, 21, 0, 0),
       datetime.datetime(2020, 10, 20, 0, 0),
       datetime.datetime(2020, 10, 16, 0, 0),
       datetime.datetime(2020, 10, 15, 0, 0),
       datetime.datetime(2020, 10, 14, 0, 0),
       datetime.datetime(2020, 10, 13, 0, 0),
       datetime.datetime(2020, 10, 12, 0, 0),
       datetime.datetime(2020, 10, 9, 0, 0),
       datetime.datetime(2020, 10, 5, 0, 0),
       datetime.datetime(2020, 10, 1, 0, 0)], dtype=object)

In [185]:
mask = ohlc[:, 3] > 116.0
mask

array([False, False,  True, False, False, False,  True,  True, False,
        True,  True,  True,  True,  True,  True, False, False, False,
        True, False,  True, False, False])

In [186]:
filtered_data = [
    [date, row]
    for date, row in zip(dates[mask], ohlc[mask])
]

for row in filtered_data:
    print(row)

[datetime.datetime(2020, 10, 27, 0, 0), array([115.49  , 117.28  , 114.5399, 116.6   ])]
[datetime.datetime(2020, 10, 21, 0, 0), array([116.67 , 118.705, 116.45 , 116.87 ])]
[datetime.datetime(2020, 10, 20, 0, 0), array([116.2 , 118.98, 115.63, 117.51])]
[datetime.datetime(2020, 10, 16, 0, 0), array([121.28 , 121.548, 118.81 , 119.02 ])]
[datetime.datetime(2020, 10, 15, 0, 0), array([118.72, 121.2 , 118.15, 120.71])]
[datetime.datetime(2020, 10, 14, 0, 0), array([121.  , 123.03, 119.62, 121.19])]
[datetime.datetime(2020, 10, 13, 0, 0), array([125.27, 125.39, 119.65, 121.1 ])]
[datetime.datetime(2020, 10, 12, 0, 0), array([120.06  , 125.18  , 119.2845, 124.4   ])]
[datetime.datetime(2020, 10, 9, 0, 0), array([115.28, 117.  , 114.92, 116.97])]
[datetime.datetime(2020, 10, 5, 0, 0), array([113.91, 116.65, 113.55, 116.5 ])]
[datetime.datetime(2020, 10, 1, 0, 0), array([117.64, 117.72, 115.83, 116.79])]


In [187]:
date = '10/1/2020'
numbers = [100, 200, 300, 400]

[date, numbers]

['10/1/2020', [100, 200, 300, 400]]

In [188]:
[date, *numbers]

['10/1/2020', 100, 200, 300, 400]

In [189]:
filtered_data = [
    [date, *row]
    for date, row in zip(dates[mask], ohlc[mask])
]

for row in filtered_data:
    print(row)

[datetime.datetime(2020, 10, 27, 0, 0), 115.49, 117.28, 114.5399, 116.6]
[datetime.datetime(2020, 10, 21, 0, 0), 116.67, 118.705, 116.45, 116.87]
[datetime.datetime(2020, 10, 20, 0, 0), 116.2, 118.98, 115.63, 117.51]
[datetime.datetime(2020, 10, 16, 0, 0), 121.28, 121.548, 118.81, 119.02]
[datetime.datetime(2020, 10, 15, 0, 0), 118.72, 121.2, 118.15, 120.71]
[datetime.datetime(2020, 10, 14, 0, 0), 121.0, 123.03, 119.62, 121.19]
[datetime.datetime(2020, 10, 13, 0, 0), 125.27, 125.39, 119.65, 121.1]
[datetime.datetime(2020, 10, 12, 0, 0), 120.06, 125.18, 119.2845, 124.4]
[datetime.datetime(2020, 10, 9, 0, 0), 115.28, 117.0, 114.92, 116.97]
[datetime.datetime(2020, 10, 5, 0, 0), 113.91, 116.65, 113.55, 116.5]
[datetime.datetime(2020, 10, 1, 0, 0), 117.64, 117.72, 115.83, 116.79]


### Universal Functions

In [1]:
import numpy as np

In [2]:
arr_1 = np.array([1, 2, 3, 4, 5])
arr_2 = np.arange(1, 6)
arr_1

array([1, 2, 3, 4, 5])

In [3]:
arr_2

array([1, 2, 3, 4, 5])

In [4]:
arr_1 + arr_2

array([ 2,  4,  6,  8, 10])

In [6]:
np.add(arr_1, arr_2)

array([ 2,  4,  6,  8, 10])

In [7]:
np.multiply(arr_1, arr_2)

array([ 1,  4,  9, 16, 25])

In [8]:
np.subtract(arr_1, arr_2)

array([0, 0, 0, 0, 0])

In [9]:
arr_1 // arr_2

array([1, 1, 1, 1, 1])

In [10]:
np.floor_divide(arr_1, arr_2)

array([1, 1, 1, 1, 1])

In [11]:
arr_1 % arr_2

array([0, 0, 0, 0, 0])

In [12]:
np.mod(arr_1, arr_2)

array([0, 0, 0, 0, 0])

In [13]:
arr_1 ** arr_2

array([   1,    4,   27,  256, 3125])

In [14]:
np.power(arr_1, arr_2)

array([   1,    4,   27,  256, 3125])

In [15]:
arr_1

array([1, 2, 3, 4, 5])

In [16]:
arr_1 ** 2

array([ 1,  4,  9, 16, 25])

In [17]:
np.power(arr_1, 2)

array([ 1,  4,  9, 16, 25], dtype=int32)

In [22]:
arr = np.linspace(-2 * np.pi, 2 * np.pi, 10)
arr

array([-6.28318531, -4.88692191, -3.4906585 , -2.0943951 , -0.6981317 ,
        0.6981317 ,  2.0943951 ,  3.4906585 ,  4.88692191,  6.28318531])

In [23]:
np.sin(arr)

array([ 2.44929360e-16,  9.84807753e-01,  3.42020143e-01, -8.66025404e-01,
       -6.42787610e-01,  6.42787610e-01,  8.66025404e-01, -3.42020143e-01,
       -9.84807753e-01, -2.44929360e-16])

In [24]:
np.cos(arr)

array([ 1.        ,  0.17364818, -0.93969262, -0.5       ,  0.76604444,
        0.76604444, -0.5       , -0.93969262,  0.17364818,  1.        ])

In [25]:
from time import perf_counter

In [26]:
l = list(range(1, 1_000_000))

In [27]:
start = perf_counter()
new_list = []
for el in l:
    new_list.append(1 / el)
end = perf_counter()
print('Elapsed time:', end - start)

Elapsed time: 0.2526454000035301


In [28]:
start = perf_counter()
new_list = [1 / el for el in l]
end = perf_counter()
print('Elapsed time:', end - start)

Elapsed time: 0.2902691999988747


In [29]:
np_l = np.array(l)

In [30]:
np_l.dtype

dtype('int32')

In [31]:
start = perf_counter()
new_arr = 1 / arr
end = perf_counter()
print('Elapsed time:', end - start)

Elapsed time: 0.00019769999926211312


In [32]:
import random

In [33]:
num_rows = 10_000_000

random.seed(0)

start = perf_counter()

data = [
    [
        random.randint(120, 180),
        random.randint(180, 200),
        random.randint(100, 120),
        random.randint(120, 180)
    ]
    for _ in range(num_rows)
]

end = perf_counter()
print(data[:2])
print('Elapsed:', end-start)

[[174, 192, 113, 122], [136, 196, 115, 145]]
Elapsed: 29.97561410000344


`round((high - low) / close * 100)`

In [34]:
start = perf_counter()
var = [
    round((row[1] - row[2]) / row[3] * 100)
    for row in data
]
end = perf_counter()
print(var[:3])
print('Elapsed:', end - start)

[65, 56, 52]
Elapsed: 2.914326300000539


In [35]:
start = perf_counter()
data_np = np.array(data)
end = perf_counter()
print(data[:2])
print('Elapsed:', end - start)

[[174, 192, 113, 122], [136, 196, 115, 145]]
Elapsed: 4.843489200000477


In [37]:
start = perf_counter()
var = np.round((data_np[:, 1] - data_np[:, 2]) / data_np[:, 3] * 100)
end = perf_counter()
print(var[:5])
print('Elapsed:', end - start)

[65. 56. 52. 55. 51.]
Elapsed: 0.289829399996961


In [39]:
np.random.seed(0)
start = perf_counter()
data_np = np.hstack(
    [
        np.random.randint(120, 180, (num_rows, 1)),
        np.random.randint(180, 200, (num_rows, 1)),
        np.random.randint(100, 120, (num_rows, 1)),
        np.random.randint(120, 180, (num_rows, 1)),
    ]
)
end = perf_counter()
print(data_np[:5])
print('Elapsed:', end - start)

[[164 181 112 125]
 [167 199 110 136]
 [173 189 106 122]
 [120 180 105 143]
 [123 199 104 122]]
Elapsed: 0.6529837999987649


In [40]:
num_rows = 10_000_000

random.seed(0)

start = perf_counter()

data = [
    [
        random.randint(120, 180),
        random.randint(180, 200),
        random.randint(100, 120),
        random.randint(120, 180)
    ]
    for _ in range(num_rows)
]

var = [
    round((row[1] - row[2]) / row[3] * 100)
    for row in data
]


end = perf_counter()
print(data[:2])
print('Elapsed:', end-start)

[[174, 192, 113, 122], [136, 196, 115, 145]]
Elapsed: 39.12460799999826


In [41]:
np.random.seed(0)
start = perf_counter()
data_np = np.hstack(
    [
        np.random.randint(120, 180, (num_rows, 1)),
        np.random.randint(180, 200, (num_rows, 1)),
        np.random.randint(100, 120, (num_rows, 1)),
        np.random.randint(120, 180, (num_rows, 1)),
    ]
)


var = np.round((data_np[:, 1] - data_np[:, 2]) / data_np[:, 3] * 100)

end = perf_counter()
print(data_np[:5])
print('Elapsed:', end - start)

[[164 181 112 125]
 [167 199 110 136]
 [173 189 106 122]
 [120 180 105 143]
 [123 199 104 122]]
Elapsed: 0.9686914000049001


In [42]:
sales = np.array(
    [
        [10, 0, 5, 3],
        [0, 0, 0, 10],
        [1, 1, 0, 0],
        [3, 0, 4, 5]
    ]
)

In [43]:
unit_price = np.array([100, 50, 20, 10])
unit_cost = np.array([80, 10, 5, 1])

In [44]:
sales * unit_price

array([[1000,    0,  100,   30],
       [   0,    0,    0,  100],
       [ 100,   50,    0,    0],
       [ 300,    0,   80,   50]])

In [46]:
total_sales = sales * unit_price

In [47]:
total_cost = sales * unit_cost
total_cost

array([[800,   0,  25,   3],
       [  0,   0,   0,  10],
       [ 80,  10,   0,   0],
       [240,   0,  20,   5]])

In [48]:
order_net = total_sales - total_cost
order_net

array([[200,   0,  75,  27],
       [  0,   0,   0,  90],
       [ 20,  40,   0,   0],
       [ 60,   0,  60,  45]])

In [49]:
sum([1, 2, 3])

6

In [50]:
np.sum(order_net)

617

### Some Additional Maths and Stats Functions

In [1]:
import numpy as np

In [2]:
np.amin(np.array([10, 5, 20]))

5

In [3]:
np.amax(np.array([10, 5, 29]))

29

In [7]:
m = np.array([[10, 2, 3], [4, 50, 60], [7, 8, 90]])
m

array([[10,  2,  3],
       [ 4, 50, 60],
       [ 7,  8, 90]])

In [8]:
np.amin(m), np.amax(m)

(2, 90)

In [9]:
np.amin(m, axis=0), np.amax(m, axis=0)

(array([4, 2, 3]), array([10, 50, 90]))

In [10]:
np.amin(m, axis=1), np.amax(m, axis=1)

(array([2, 4, 7]), array([10, 60, 90]))

In [11]:
np.median(np.array([1, 2, 3, 4, 5]))

3.0

In [12]:
np.median(np.array([1, 2, 3, 4, 5, 6]))

3.5

In [13]:
np.mean(np.array([1, 2, 3]))

2.0

In [14]:
np.std(np.array([-2, -1, 0, 1, 2]))

1.4142135623730951

In [15]:
m = np.array(
    [
        [1, 10, 100],
        [2, 20, 200],
        [3, 30, 300],
        [3, 30, 300],
        [4, 40, 400]
    ]
)

In [16]:
np.mean(m)

96.2

In [17]:
np.median(m)

30.0

In [18]:
np.mean(m, axis=0)

array([  2.6,  26. , 260. ])

In [19]:
np.median(m, axis=0)

array([  3.,  30., 300.])

In [21]:
np.mean(m, axis=1)

array([ 37.,  74., 111., 111., 148.])

In [22]:
np.median(m, axis=1)

array([10., 20., 30., 30., 40.])

In [24]:
np.sum(np.arange(1, 10))

45

In [25]:
m = np.arange(1, 10).reshape(3, 3)
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
np.sum(m)

45

In [28]:
np.sum(m, axis=0)

array([12, 15, 18])

In [29]:
np.sum(m, axis=1)

array([ 6, 15, 24])

In [30]:
arr = np.array([1.11, 2.22, 5.55, 6.66])
np.around(arr, 1)

array([1.1, 2.2, 5.6, 6.7])

In [31]:
np.around(arr)

array([1., 2., 6., 7.])

In [32]:
np.around(np.array([123, 155]), -2)

array([100, 200])

In [33]:
np.random.seed(0)

arr = np.random.randint(1, 10, 20)
arr

array([6, 1, 4, 4, 8, 4, 6, 3, 5, 8, 7, 9, 9, 2, 7, 8, 8, 9, 2, 6])

`[0, 2), [2, 4) [4, 6) [6, 8) [8, 9]`

In [34]:
bins = np.array([0, 2, 4, 6, 8, 9])

In [35]:
np.histogram(arr, bins=bins)

(array([1, 3, 4, 5, 7], dtype=int64), array([0, 2, 4, 6, 8, 9]))

In [36]:
np.histogram(arr, bins=4)

(array([3, 4, 4, 9], dtype=int64), array([1., 3., 5., 7., 9.]))